{ inputs, ... }:
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  flake.modules.nixos.host_vmware =
    {
      config,
      lib,
      ...
    }:
    {

      boot = {
        initrd.availableKernelModules = [
          "ata_piix"
          "mptspi"
          "uhci_hcd"
          "ehci_pci"
          "ahci"
          "sd_mod"
          "sr_mod"
        ];
        initrd.kernelModules = [ ];
        kernelModules = [ ];
        extraModulePackages = [ ];
      };

      hardware.enableRedistributableFirmware = true;
    };
}